config/routes.rb
Rails.application.routes.draw do
  root       "top#index"

  resources  :top

  devise_for :users

  resources  :users

  resources  :tweets do
    collection do
      get 'search'
      get 'eat'
      get 'event'
      get 'trip'
    end
    resources :comments, only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  acts_as_taggable

  belongs_to :user
  has_many   :comments

  has_attached_file :movie, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :movie, content_type: ["image/jpg","image/jpeg","image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  acts_as_tagger
  has_many :tweets
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.where(genre: @genre)
    # @tags = ActsAsTaggableOn::Tag.most_used
  end

  def new
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id]).update(tweet_params)
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.user_id == current_user.id
      @tweet.destroy
    end
  end

  def search
    @tweets1 = Tweet.where('title LIKE(?)', "%#{params[:keyword]}%")
    @tweets2 = Tweet.where('text LIKE(?)', "%#{params[:keyword]}%")
    @tweets3 = Tweet.tagged_with("#{params[:keyword]}")
  end

  def eat
    @tweets = Tweet.where(genre: 'eat')
  end

  def event
    @tweets = Tweet.where(genre: 'event')
  end

  def trip
    @tweets = Tweet.where(genre: 'trip')
  end

  private
  def tweet_params
    params.require(:tweet).permit(:genre, :tag_list , :text ,:title , :movie).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: current_user.id).order("id DESC")
  end

  def edit
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/common/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
<%= link_to "Original APP",root_path %>

<%= form_tag('/tweets/search', method: :get) do %>
  <input name="keyword" placeholder="検索" type="text" value=""></input>
  <button title="検索" type="submit"></button>
<% end %>

<% if user_signed_in? %>
  <%= link_to "投稿", new_tweet_path %>
  <%= link_to "マイページ", user_path(current_user) %>
  <%= link_to 'プロフィール変更', edit_user_path(current_user) %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'サインアップ', new_user_registration_path %>
  <%= link_to 'ログイン', new_user_session_path %>
<% end %>
</div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OriginalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render partial: "common/header" %>
<%= bootstrap_flash %>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<dl>
  <dt>カテゴリー</dt>
  <dd><%= link_to "グルメ", eat_tweets_path %></dd>
  <dd><%= link_to "イベント", event_tweets_path %></dd>
  <dd><%= link_to "旅行", trip_tweets_path, method: :get, genre: "trip" %></dd>
</dl>

<h4>グルメの最新投稿</h4>
  <% @tweets.where("genre = 'eat'").each do |tweet| %>
  <div style="background-image: url(<%= tweet.movie %>);">
    <ul>
      <li><%= tweet.title %></li>
      <li><%= tweet.text %></li>
      <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>

      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>

        <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h4>イベントの最新投稿</h4>
  <% @tweets.where("genre = 'event'").each do |tweet| %>
  <div style="background-image: url(<%= tweet.movie %>);">
    <ul>
      <li><%= tweet.title %></li>
      <li><%= tweet.text %></li>
      <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>

      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>

        <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<h4>旅行の最新投稿</h4>
  <% @tweets.where("genre = 'trip'").each do |tweet| %>
    <div style="background-image: url(<%= tweet.movie %>);">
      <ul>
        <li><%= tweet.title %></li>
        <li><%= tweet.text %></li>
        <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>

        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>
          <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/tweets/_form.html.erb
<%= form_for @tweet do |f| %>
  <ul>
    <li>タイトル</li>
    <%= f.text_field :title, placeholder: "タイトル" %>

    <li>ジャンル</li>
    <%= f.select :genre, [['グルメ', 'eat'], ['旅行', 'trip'], ['イベント', 'event']], prompt: '選択してください' %>

    <li>タグ</li>
    <%= f.text_field :tag_list, placeholder: "タグ" %>

    <li>コメント</li>
    <%= f.text_area :text, placeholder: "コメント" %>

    <li>画像/動画</li>
    <%= f.file_field :movie %>

    <%= f.submit "投稿する"%>
  </ul>
<% end %>

app/views/tweets/create.html.erb
<h3>投稿が完了しました。</h3>
<%= link_to "HOMEへ戻る", root_path %>

app/views/tweets/destroy.html.erb
<h3>削除が完了しました。</h3>
<%= link_to "HOMEへ戻る", root_path %>

app/views/tweets/eat.html.erb
<h4>グルメの最新投稿</h4>
  <% @tweets.each do |tweet| %>
  <div style="background-image: url(<%= tweet.movie %>);">
    <ul>
      <li><%= tweet.title %></li>
      <li><%= tweet.text %></li>
      <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>

      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>

        <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/tweets/edit.html.erb
<%= form_for(@tweet) do |f| %>
  <ul>
    <li>タイトル</li>
    <%= f.text_field :title, placeholder: "タイトル" %>

    <li>ジャンル</li>
    <%= f.select :genre, [['グルメ', 'eat'], ['旅行', 'trip'], ['イベント', 'event']], prompt: '選択してください' %>

    <li>タグ</li>
    <%= f.text_field :tag_list, placeholder: "タグ" %>

    <li>コメント</li>
    <%= f.text_area :text, placeholder: "コメント" %>

    <li>画像/動画</li>
    <%= f.file_field :movie %>

    <%= f.submit "投稿する"%>
  </ul>
<% end %>

app/views/tweets/event.html.erb
<h4>イベントの最新投稿</h4>
  <% @tweets.each do |tweet| %>
  <div style="background-image: url(<%= tweet.movie %>);">
    <ul>
      <li><%= tweet.title %></li>
      <li><%= tweet.text %></li>
      <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>

      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>

        <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/tweets/new.html.erb
<h1>New Pop</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/tweets/search.html.erb
<p>タイトルに<%= "#{params[:keyword]}" %>を含む</p>
<% @tweets1.each do |a| %>
  <p><%= a.id %></p>
<% end %>

<p>コメントに<%= "#{params[:keyword]}" %>を含む</p>
<% @tweets2.each do |b| %>
  <p><%= b.id %></p>
<% end %>

<p>タグに<%= "#{params[:keyword]}" %>を含む</p>
<% @tweets3.each do |c| %>
  <p><%= c.id %></p>
<% end %>

app/views/tweets/show.html.erb
<div style="background-image: url(<%= @tweet.movie %>);">
  <ul>
    <li><%= @tweet.title %></li>
    <li><%= @tweet.text %></li>
    <li><%= link_to '詳細', tweet_path(@tweet.id), method: :get %></li>

    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <li><%= link_to '編集', edit_tweet_path(@tweet.id) %></li>
      <li><%= link_to '削除', tweet_path(@tweet.id), method: :delete %></li>
    <% end %>

  </ul>
</div>

<div>
  <% if current_user %>
    <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
      <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
      <input type="submit" value="SENT">
    <% end %>
  <% end %>
</div>

<div>
  <h4>＜コメント一覧＞</h4>
    <% if @comments %>
      <% @comments.each do |comment| %>
      <p>
        <storng><%= link_to comment.user.family_name, user_path(comment.user_id), method: :get %>：</strong>
        <%= comment.text %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/tweets/trip.html.erb
<h4>旅行の最新投稿</h4>
  <% @tweets.each do |tweet| %>
    <div style="background-image: url(<%= tweet.movie %>);">
      <ul>
        <li><%= tweet.title %></li>
        <li><%= tweet.text %></li>
        <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>

        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>
          <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/tweets/update.html.erb
<h3>編集が完了しました。</h3>
<%= link_to "HOMEへ戻る", root_path %>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
  <h2>プロフィール画像</h2>
  <%= f.file_field :avatar, placeholder: "画像アップロード" %>

  <h2>登録情報</h2>
  <%= f.text_field :family_name, placeholder: "姓" %>
  <%= f.text_field :first_name, placeholder: "名" %>
  <%= f.text_field :family_name_kana, placeholder: "セイ" %>
  <%= f.text_field :first_name_kana, placeholder: "メイ" %>

  <%= f.submit "送信" %>
<% end %>

app/views/users/show.html.erb
<h3>プロフィール画像</h3>
<%= image_tag @user.avatar.url(:medium) %>

<h3><%= @user.name %></br>
<%= @user.name_kana %></h3>

<h4><%= @user.name %>さんの最新投稿</h4>
  <% @tweets.each do |tweet| %>
  <div style="background-image: url(<%= tweet.movie %>);">
    <ul>
      <li><%= tweet.title %></li>
      <li><%= tweet.text %></li>
      <li><%= link_to '詳細', tweet_path(tweet.id), method: :get %></li>

      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li><%= link_to '編集', edit_tweet_path(tweet.id) %></li>

        <li><%= link_to '削除', tweet_path(tweet.id), method: :delete %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/users/update.html.erb
<h3>プロフィールの編集が完了しました。</h3>
<%= link_to "ホームに戻る", root_path %>